# LAB | Two Sample Hypothesis Tests

### Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import seaborn as sns

## Challenge 1 - Independent Sample T-tests

In this challenge, we will be using the Pokemon dataset. Before applying statistical methods to this data, let's first examine the data.

To load the data, run the code below.

In [3]:
# Run this code:

pokemon = pd.read_csv('https://raw.githubusercontent.com/Dee-M123/lab-dsai-two-sample-hypothesis-tests/refs/heads/main/data/Pokemon.csv')

Let's start off by looking at the `head` function in the cell below.

In [4]:
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

The first thing we would like to do is compare the legendary Pokemon to the regular Pokemon. To do this, we should examine the data further. What is the count of legendary vs. non legendary Pokemons?

In [5]:
pokemon['Legendary'].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

Compute the mean and standard deviation of the total points for both legendary and non-legendary Pokemon.

In [6]:
pokemon.groupby('Legendary')['Total'].agg(['mean', 'std'])

                 mean         std
Legendary
False      417.213605  106.760417
True       637.384615   60.937389

The computation of the mean might give us a clue regarding how the statistical test may turn out; However, it certainly does not prove whether there is a significant difference between the two groups.

In the cell below, use the `ttest_ind` function in `scipy.stats` to compare the the total points for legendary and non-legendary Pokemon. Since we do not have any information about the population, assume the variances are not equal.

In [8]:
from scipy.stats import ttest_ind

# Two groups: legendary and non legendary

legendary = pokemon[pokemon['Legendary'] == True]['Total']
non_legendary = pokemon[pokemon['Legendary'] == False]['Total']

# H_0: legendary = on legendary
# H_0: legendary != on legendary

# independent test
t_stat, p_value = ttest_ind(legendary, non_legendary, alternative="two-sided", equal_var=False)

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 25.8335743895517
p-value: 9.357954335957446e-47

What do you conclude from this test? Write your conclusions below.

In [ ]:
# The extremely small p-value also indicates very strong evidence that the difference between the two groups is not due to random chance

How about we try to compare the different types of pokemon? In the cell below, list the types of Pokemon from column `Type 1` and the count of each type.

In [10]:
pokemon['Type 1'].value_counts().sort_index()

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count, dtype: int64

Since water is the largest group of Pokemon, compare the mean and standard deviation of water Pokemon to all other Pokemon.

In [14]:
# Create two groups
water = pokemon[pokemon['Type 1'] == 'Water']['Total']
non_water = pokemon[pokemon['Type 1'] != 'Water']['Total']

# mean and standard deviation
print("Water Pokémon")
print("Mean:", water.mean())
print("Standard Deviation:", water.std())

print("\nNon_Water Pokémon")
print("Mean:", non_water.mean())
print("Standard Deviation:", non_water.std())

Water Pokémon
Mean: 430.45535714285717
Standard Deviation: 113.18826606431458

Non_Water Pokémon
Mean: 435.85901162790697
Standard Deviation: 121.09168230208066

Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon. Assume the variances are equal.

In [16]:
# H_0: water = others
# H_1: water != others

t_stat, p_value = ttest_ind(water, non_water,alternative="two-sided", equal_var=True)

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: -0.4418547448849676
p-value: 0.6587140317488793

Write your conclusion below.

In [ ]:
# failed to reject H_0; no statistically significant difference in the mean total points between Water Pokémon and non-Water Pokémon

# Challenge 2 - Matched Pairs Test

In this challenge we will compare dependent samples of data describing our Pokemon. Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. In the cell below, import the `ttest_rel` function from `scipy.stats` and compare the two columns to see if there is a statistically significant difference between them.

In [18]:
from scipy.stats import ttest_rel

attack = pokemon['Attack']
defense = pokemon['Defense']
# H_0: attack = defense
# H_1: attack != defense

# Perform paired t-test
t_stat, p_value = ttest_rel(attack, defense, alternative="two-sided")

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 4.325566393330478
p-value: 1.7140303479358558e-05

Describe the results of the test in the cell below.

In [ ]:
# we reject the null hypothesis that the mean Attack and Defense scores are equal.

We are also curious about whether therer is a significant difference between the mean of special defense and the mean of special attack. Perform the hypothesis test in the cell below.

In [19]:
s_attack = pokemon['Sp. Atk']
s_defense = pokemon['Sp. Def']
# H_0: s_attack = s_defense
# H_1: s_attack != s_defense

# paired t-test
t_stat, p_value = ttest_rel(s_attack, s_defense, alternative="two-sided")

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 0.853986188453353
p-value: 0.3933685997548122

Describe the results of the test in the cell below.

In [ ]:
# fail to reject the null hypothesis

As you may recall, a two sample matched pairs test can also be expressed as a one sample test of the difference between the two dependent columns.

Import the `ttest_1samp` function and perform a one sample t-test of the difference between defense and attack. Test the hypothesis that the difference between the means is zero. Confirm that the results of the test are the same.

In [21]:
from scipy.stats import ttest_1samp
# difference between Attack and Defense
diff = attack - defense

#H_0: diff = 0
#H_1: diff != 0

# One-sample t-test (testing if mean difference = 0)
t_stat, p_value = ttest_1samp(diff, 0)

print("t-statistic:", t_stat)
print("p-value:", p_value)

t-statistic: 4.325566393330478
p-value: 1.7140303479358558e-05

In [ ]:
# we reject the null hypothesis that the mean difference between Attack and Defense is zero

# Bonus Challenge - The Chi-Square Test

The Chi-Square test is used to determine whether there is a statistically significant difference in frequencies. In other words, we are testing whether there is a relationship between categorical variables or rather when the variables are independent. This test is an alternative to Fisher's exact test and is used in scenarios where sample sizes are larger. However, with a large enough sample size, both tests produce similar results. Read more about the Chi Squared test [here](https://en.wikipedia.org/wiki/Chi-squared_test).

In the cell below, create a contingency table using `pd.crosstab` comparing whether a Pokemon is legenadary or not and whether the Type 1 of a Pokemon is water or not.

In [ ]:
# Your code here:

Perform a chi-squared test using the `chi2_contingency` function in `scipy.stats`. You can read the documentation of the function [here](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html).

In [ ]:
# Your code here:

Based on a 95% confidence, should we reject the null hypothesis?

In [ ]:
# Your answer here: